### ISSUE TITLE
Link on docker-hub

### ISSUE THREAD

**Issue by RomainTT** [Harvester57/Dockerfiles#1]
Hi ! I found your images on [docker hub](https://hub.docker.com/u/fstossesds), thanks by the way !

I just wanted to tell you that the links to your Github repositories are not up to date, like [here](https://hub.docker.com/r/fstossesds/cpplint)

**Comment by Harvester57** [comment]
Hi !

Thanks for the heads-up, the repositories are in fact still there, they just went private (I don't remember exactly why I did it, I believe it has something to do with the Auto-Build functionnality of the Docker Hub, that is now a paid functionnality...)

I will make them public again, and try to update the repo (the Dockerfiles are not as up-to-date as you'd like them to be, I guess :))

**Comment by Harvester57** [comment]
Okay, I updated this master repo and I switched back the other repos to public :)

Since there is no Auto-Build anymore on Docker Hub, I will switch to GitHub Actions to build and push images in the future. Let me know if you have some ideas to improve the current images ! :)

**Comment by RomainTT** [comment]
Thank you very much ! These images are already fine, but if I have some ideas I’ll tell you.
